services:
  query:
    environment:
      # Use shared-services MongoDB and REDIS
      - MONGO_URI=mongodb://mongodb:27017
      - REDIS_URL=redis://redis:6379

  query_python:
    environment:
      # Use shared-services MongoDB and REDIS
      - MONGO_URI=mongodb://mongodb:27017
      - REDIS_URL=redis://redis:6379
